
// function getPromise(){
//     return new Promise((resolve, reject) => {
//         setTimeout(() => {
//             const randomNumber = Math.random()

//             console.log(randomNumber)

//             if( randomNumber < 0.5){
//                 resolve("Promise Resolved")
//             } else{
//                 reject("Promise Rejected")
//             }

//         }, 2000)
//     })
// }

// getPromise().then(result => {
//     console.log(result)

// }).catch(error =>{
//     console.log("There was an error")
// })

// console.log("This is after we get")